version: '3.3'

services:
    web:
        build:
            context: .
            dockerfile: ./docker/web/Dockerfile
        restart: unless-stopped
        container_name: ${PROJECT_NAME}-web
        entrypoint: /srv/www/docker/web/wsgi-entrypoint.sh
        ports:
            - ${HOST_PORT}:80
        volumes:
            - ./:/srv/www/
        env_file:
            - ./.env
        depends_on:
            - database

    database:
        image: postgres:13-alpine
        container_name: ${PROJECT_NAME}-database
        volumes:
            - ./docker/postgresql/data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_DB=${SQL_DATABASE}
            - POSTGRES_USER=${SQL_USER}
            - POSTGRES_PASSWORD=${SQL_PASSWORD}

