version: '3.9'

services:

  backend:
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./docker/backend/Dockerfile
    container_name: vlknn-backend
    entrypoint: /usr/src/app/docker/backend/wsgi-entrypoint.sh
    ports:
        - 80:8000
    volumes:
      - ./docker/:/usr/src/app/docker/
      - ./:/usr/src/app/backend/